### ISSUE TITLE
Make setter for properties in CarModel public instead of protected

### ISSUE THREAD

**Issue by suikerr** [jgveire/Vanguard.Framework#1]
Properties LicensePlate and IsStolen have a protected set
````
[Required]
[MaxLength(20)]
public string LicensePlate { get; protected set; }

[Required]
public bool IsStolen { get; protected set; }
````
I think this prevents the modelbinder from setting them, causing validation errors

**Comment by jgveire** [comment]
Sorry for the late reply but the issue has been fixed.
39fb595fc6769904d9ed8808f17438990bf95f3d
